name: Add Links
# Runs on pushes targeting the default branch
on:
  push:
    branches: ["main"]

jobs:
  addLinks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/checkout@v4
      
      - name: Add the Prev and Next links
        run: util/makeLinks.sh

      - name: Commit the changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Links added'
          add: 'docs/*.md'