name: Linting
on: [push]

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/checkout@v3
      - uses: errata-ai/vale-action@reviewdog
        with:
          files: docs
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
